### PR TITLE
Fix deprecation warning with Django 1.7+

### PR DESCRIPTION
**Pull request by davidfischer-ch**

### CODE REVIEW

**Comment by carltongibson** [comment]
I was just about to make this fix myself. This should work. 

@jezdez — Any chance you can restart the build on this? (There was an error but the fix itself looks good.)

It would be great if this could be merged and put on PyPI... :-)

I'm happy to contribute if that would help.

**Comment by davidfischer-ch** [comment]
Are you kidding me?

**Comment by jezdez** [comment]
@davidfischer-ch No, I merged #15.

**Comment by davidfischer-ch** [comment]
I know, why did you never replied to my pull request? That's the same fix
11 months earlier.

**Comment by jezdez** [comment]
@davidfischer-ch Honestly, because I have a huge amount of GitHub notifications that I often have to declare inbox bankruptcy for. @paltman's PR just happened to show up in a almost empty mailbox situation. No offense to you or your code intended.

**Comment by davidfischer-ch** [comment]
I am a lucky developer using your project into mines and thought it was a
good way to thank you and the community. Unfortunately my work went to
trash.

**Comment by jezdez** [comment]
@davidfischer-ch Yeah, that really sucks, and I apologize for that. Last thing I want is to alienate contributors like you. Hopefully I can make things right when you do you next contribution.

**Comment by carltongibson** [comment]
@jezdez: just to say again, I'm happy to help maintain here. (I'm both using the app and know you're busy)

**Comment by davidfischer-ch** [comment]
Is it thanksgiving ;-)

Happy Sunday dear developers.

**Pull request closed without merging**
